name: Docker Build
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update source
      run: |
        bash mantic.sh

    - name: Commit changes
      run: |
        ${{ secrets.cr }}
        git config --local user.email "angga@linuxmail.org"
        git config --local user.name "Angga"
        git config --global --add safe.directory /github/workspace
        git add -A
        git commit -s -am "$(curl -s https://raw.githubusercontent.com/ngerakines/commitment/main/commit_messages.txt | shuf -n 1)"

    - name: GitHub Push
      uses: ad-m/github-push-action@master
      with:
        force: true
        directory: "."
        github_token: ${{ secrets.GITHUB_TOKEN }}   
        
    - name: Build and Publish to Dockerhub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: gengkapak/mantic
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest
